version: "3.8"

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=minigest.settings.docker
      - NODE_ENV=production
    volumes:
      - .:/var/www/minigest
      - public:/var/www/minigest/public
    depends_on:
      - db

volumes:
  db_volume:
  public:
