# Generated by Django 3.0.6 on 2020-05-25 12:19

import common.models.fields.uppercase
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import docfisc.helpers.docfisc.updirs
import localflavor.generic.models
import minigest.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0002_domiciliofiscale_domiciliostabileorganizzazione_impresa_personafisica_soggettofiscale'),
        ('negozi', '0001_initial'),
        ('tributi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiusuraFiscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('totale_doc', models.PositiveIntegerField(default=1, help_text='il numero totale dei documenti fiscali o scontrini emessi', verbose_name='Totale documenti emessi')),
                ('sconti', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiusure', to='negozi.Cassa')),
            ],
            options={
                'verbose_name_plural': 'Chiusure fiscali',
            },
        ),
        migrations.CreateModel(
            name='CodiceDocumentoFiscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', common.models.fields.uppercase.UpperCaseField(max_length=5, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo di documento fiscale',
                'verbose_name_plural': 'Tipi di documento fiscale',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='CondizionePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', common.models.fields.uppercase.UpperCaseField(max_length=5, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Condizioni Pagamento',
            },
        ),
        migrations.CreateModel(
            name='ModalitaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', common.models.fields.uppercase.UpperCaseField(max_length=5, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Modalità di pagamento',
                'verbose_name_plural': 'Modalità di pagamento',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='NaturaOperazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', common.models.fields.uppercase.UpperCaseField(max_length=5, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Natura operazione',
                'verbose_name_plural': 'Natura delle operazioni',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('data', models.DateField(help_text='data di emissione')),
                ('data_ricezione', models.DateField(blank=True, help_text='data di ricezione SDI', null=True)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('xml', models.FileField(blank=True, max_length=1000, null=True, storage=minigest.storage.CustomStorage(), upload_to=docfisc.helpers.docfisc.updirs.dir_docfisc_xml)),
                ('cedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docfisc_vendita', to='anagrafica.Impresa')),
                ('codice_documento', models.ForeignKey(db_column='codice_documento', default='TD01', on_delete=django.db.models.deletion.PROTECT, related_name='docfisc', to='docfisc.CodiceDocumentoFiscale', to_field='codice')),
                ('committente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docfisc_acquisto', to='anagrafica.SoggettoFiscale')),
                ('condizioni_pagamento', models.ForeignKey(blank=True, db_column='condizioni_pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='docfisc.CondizionePagamento', to_field='codice')),
            ],
            options={
                'verbose_name_plural': 'Documenti Fiscali',
            },
        ),
        migrations.CreateModel(
            name='DocFiscScadenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('beneficiario', models.CharField(blank=True, help_text='beneficiario del pagamento se diverso dal cedente', max_length=200, null=True)),
                ('data_riferimento_termini_pagamento', models.DateField(blank=True, help_text='data dalla quale decorrono i termini di pagamento', null=True)),
                ('giorni_termini_pagamento', models.IntegerField(blank=True, help_text='termini di pagamento espressi in giorni\n            a partire dalla data di riferimento termini pagamento', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cod_ufficio_postale', models.CharField(blank=True, help_text="Nei casi di modalità di pagamento\n            in cui ha senso l'indicazione dell'ufficio postale", max_length=20, null=True)),
                ('nome_quietanzante', models.CharField(blank=True, help_text='Nel caso di pagamento con contanti presso Tesoreria', max_length=60, null=True)),
                ('cognome_quietanzante', models.CharField(blank=True, help_text='Nel caso di pagamento con contanti presso Tesoreria', max_length=60, null=True)),
                ('cf_quietanzante', models.CharField(blank=True, help_text='Nel caso di pagamento con contanti presso Tesoreria', max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('titolo_quietanzante', models.CharField(blank=True, help_text='Nel caso di pagamento con contanti presso Tesoreria', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('istituto_finanziario', models.CharField(blank=True, help_text='nome della banca o istituto finanziario', max_length=80, null=True)),
                ('iban', localflavor.generic.models.IBANField(blank=True, help_text='coordinata bancaria internazionale', include_countries=('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GI', 'GR', 'HR', 'HU', 'IE', 'IS', 'IT', 'LI', 'LT', 'LU', 'LV', 'MC', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK', 'SM'), max_length=34, null=True, use_nordea_extensions=False, verbose_name='IBAN')),
                ('abi', models.CharField(blank=True, help_text='codice ABI', max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ABI')),
                ('cab', models.CharField(blank=True, help_text='codice CAB', max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='CAB')),
                ('bic', localflavor.generic.models.BICField(blank=True, help_text='codice BIC', max_length=11, null=True, verbose_name='BIC')),
                ('sconto_pagamento_anticipato', models.DecimalField(blank=True, decimal_places=2, help_text='Ammontare dello sconto per pagamento anticipato', max_digits=15, null=True)),
                ('data_limite_pagamento_anticipato', models.DateField(blank=True, help_text='Data limite stabilita per il pagamento anticipato', null=True)),
                ('penalita_pagamenti_ritardati', models.DecimalField(blank=True, decimal_places=2, help_text='Ammontare della penalità dovuta per pagamenti ritardati', max_digits=15, null=True)),
                ('data_decorrenza_penale', models.DateField(blank=True, help_text='Data di decorrenza della penale', null=True)),
                ('codice_pagamento', models.CharField(blank=True, help_text='Codice per la riconciliazione degli incassi da parte del cedente', max_length=60, null=True)),
                ('docfisc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='docfisc.DocumentoFiscale')),
                ('modalita_pagamento', models.ForeignKey(blank=True, db_column='modalita_pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='docfisc.ModalitaPagamento', to_field='codice')),
            ],
            options={
                'verbose_name': 'Dettagli scadenza documento fiscale',
                'verbose_name_plural': 'Dettagli scandenze documento fiscale',
            },
        ),
        migrations.CreateModel(
            name='DocFiscRiepilogoIva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spese_accessorie', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=19, null=True)),
                ('arrotondamento', models.DecimalField(blank=True, decimal_places=2, default=None, help_text="eventuale arrotondamento dell'imponibile", max_digits=19, null=True)),
                ('imponibile', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('imposta', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('esigibilita_iva', models.CharField(blank=True, choices=[('I', 'immediata'), ('D', 'differita'), ('S', 'scissione dei pagamenti')], default='I', help_text="esprime il momento nel quale l'IVA diventa esigibile", max_length=1, null=True)),
                ('riferimento_normativo', models.CharField(blank=True, help_text='Norma di riferimento nel caso in cui la natura si valorizzata', max_length=100, null=True)),
                ('docfisc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riepiloghi_iva', to='docfisc.DocumentoFiscale')),
                ('natura', models.ForeignKey(blank=True, db_column='natura', default=None, help_text="motivo per il quale non si è\n            indicata l'aliquota iva (operazioni esenti)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='docfisc.NaturaOperazione', to_field='codice')),
                ('reparto_iva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tributi.IvaAliquota')),
            ],
            options={
                'verbose_name': 'Riepiloghi IVA dei documenti fiscali',
            },
        ),
        migrations.CreateModel(
            name='DocFiscPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('interessi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sanzione', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quietanza', models.FileField(blank=True, max_length=1000, null=True, storage=minigest.storage.CustomStorage(), upload_to=docfisc.helpers.docfisc.updirs.dir_docfisc_quietanza)),
                ('docfisc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='docfisc.DocumentoFiscale')),
                ('modalita_pagamento', models.ForeignKey(blank=True, db_column='modalita_pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='docfisc.ModalitaPagamento', to_field='codice')),
            ],
            options={
                'verbose_name': 'Dettagli pagamento documento fiscale',
                'verbose_name_plural': 'Dettagli pagamenti documento fiscale',
            },
        ),
        migrations.CreateModel(
            name='ChiusuraRepartoIva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_reparto', models.CharField(choices=[('O', 'Ordinaria'), ('R', 'Ridotta'), ('M', 'Minima'), ('E', 'Esente')], default='O', max_length=1)),
                ('totale_lordo', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('non_riscosso', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('annulli', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('resi', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('chiusura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparti', to='docfisc.ChiusuraFiscale')),
            ],
            options={
                'verbose_name': 'Reparto IVA chiusura fiscale',
                'verbose_name_plural': 'Reparti IVA chiusura fiscale',
            },
        ),
    ]
