# Generated by Django 3.0.8 on 2020-07-16 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IvaAliquota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text="la data dalla quale l'aliquota entra in vigore")),
                ('descrizione', models.CharField(choices=[('O', 'Ordinaria'), ('R', 'Ridotta'), ('M', 'Minima'), ('E', 'Esente')], default='O', max_length=1)),
                ('aliquota', models.DecimalField(decimal_places=2, default=0, help_text="l'ammontare dell'aliquota, per esempio 22", max_digits=19, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Aliquota IVA',
                'verbose_name_plural': 'Aliquote IVA',
                'ordering': ('-data', '-aliquota'),
            },
        ),
    ]
