# Generated by Django 3.0.8 on 2020-07-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soggettofiscale',
            name='rappresentante_fiscale',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafica.SoggettoFiscale'),
        ),
    ]
