# Generated by Django 3.0.8 on 2020-07-17 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0002_soggettofiscale_rappresentante_fiscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresa',
            name='denominazione',
            field=models.CharField(blank=True, default=None, help_text="la denominazione dell'impresa o il nome e cognome", max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='impresa',
            name='pec',
            field=models.EmailField(blank=True, default=None, max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='soggettofiscale',
            name='cognome',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='soggettofiscale',
            name='nome',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
