# Generated by Django 3.0.6 on 2020-05-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisco', '0001_initial'),
        ('anagrafica', '0002_auto_20200525_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresa',
            name='regime_fiscale',
            field=models.ForeignKey(default='RF01', on_delete=django.db.models.deletion.PROTECT, related_name='imprese', to='fisco.RegimeFiscale', to_field='codice'),
            preserve_default=False,
        ),
    ]
