# Generated by Django 3.0.7 on 2020-06-10 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0005_relazioneaziendale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relazioneaziendale',
            name='impresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utenti', to='anagrafica.Impresa'),
        ),
        migrations.AlterField(
            model_name='relazioneaziendale',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imprese', to=settings.AUTH_USER_MODEL),
        ),
    ]
