/* Tutte le costanti del client */

// ALIQUOTE IVA Q (correnti)
export const IVA_ALIQUOTE_Q_GET_START = "IVA_ALIQUOTE_Q_GET_START";
export const IVA_ALIQUOTE_Q_GET_SUCCESS = "IVA_ALIQUOTE_Q_GET_SUCCESS";
export const IVA_ALIQUOTE_Q_GET_FAIL = "IVA_ALIQUOTE_Q_GET_FAIL";

// ALIQUOTE IVA
export const IVA_ALIQUOTE_GET_START = "IVA_ALIQUOTE_GET_START";
export const IVA_ALIQUOTE_GET_SUCCESS = "IVA_ALIQUOTE_GET_SUCCESS";
export const IVA_ALIQUOTE_GET_FAIL = "IVA_ALIQUOTE_GET_FAIL";
export const IVA_ALIQUOTE_POST_START = "IVA_ALIQUOTE_POST_START";
export const IVA_ALIQUOTE_POST_SUCCESS = "IVA_ALIQUOTE_POST_SUCCESS";
export const IVA_ALIQUOTE_POST_FAIL = "IVA_ALIQUOTE_POST_FAIL";
export const IVA_ALIQUOTE_PUT_START = "IVA_ALIQUOTE_PUT_START";
export const IVA_ALIQUOTE_PUT_SUCCESS = "IVA_ALIQUOTE_PUT_SUCCESS";
export const IVA_ALIQUOTE_PUT_FAIL = "IVA_ALIQUOTE_PUT_FAIL";
export const IVA_ALIQUOTE_DELETE_START = "IVA_ALIQUOTE_DELETE_START";
export const IVA_ALIQUOTE_DELETE_SUCCESS = "IVA_ALIQUOTE_DELETE_SUCCESS";
export const IVA_ALIQUOTE_DELETE_FAIL = "IVA_ALIQUOTE_DELETE_FAIL";
