/* Tutte le costanti del client */

// ALIQUOTE IVA
export const IVA_ALIQUOTE_GET_START = "IVA_ALIQUOTE_GET_START";
export const IVA_ALIQUOTE_GET_SUCCESS = "IVA_ALIQUOTE_GET_SUCCESS";
export const IVA_ALIQUOTE_GET_FAIL = "IVA_ALIQUOTE_GET_FAIL";

// ALIQUOTE IVA Q (correnti)
export const IVA_ALIQUOTE_Q_GET_START = "IVA_ALIQUOTE_Q_GET_START";
export const IVA_ALIQUOTE_Q_GET_SUCCESS = "IVA_ALIQUOTE_Q_GET_SUCCESS";
export const IVA_ALIQUOTE_Q_GET_FAIL = "IVA_ALIQUOTE_Q_GET_FAIL";
