name: Docker

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pubblica su Docker HUB
        uses: docker/build-push-action@v1
        with:
          username: dcdeiv
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dcdeiv/minigest
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
