name: PyPi Package

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1
        with:
          python_version: "3.8.2"
          poetry_version: "===1.0.9"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
